RawdataPaths:
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20230120_HMK2GDSX3_Malaysia_samples_run1/RawData"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20230227_HGMH3DMXY_Malaysia_samples_run2/RawData"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20230308_Malaysia_samples_run3/RawData"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20180612_KE_japan_metagenomes/data"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20170310_WINDU179/data"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20151119_WINDU89/data"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20160415_OBIWAN225/data"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20161216_OBIWAN275/data"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20170426_OBIWAN300/data"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20170428_WINDU191/data"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20211018_A01223-105-HC32VDSX2_India_samples_run1"
  - "/work/FAC/FBM/DMF/pengel/spirit/aprasad/NGS_data/20211102_A01223-109-HC2KGDSX2_India_samples_run2"
Adapters:
  SAMPLES_KE: "config/NexteraPE-PE.fa"
  SAMPLES_KE_CHOSEN: "config/NexteraPE-PE.fa"
  # consider putting this in as a checkpoint if this needs to be made from index_table later
  SAMPLES_INDIA: "config/Adpaters-PE.fa"
  default: "config/NexteraPE-PE.fa"
TYPES:
  - "paired"
  - "unpaired"
ProjectIdentifier: "211018_Medgenome_india_samples"
GENOME_DBs:
  host: "4_host_db"
  microbiome_red: "honeybee_gut_microbiota_db_red"
  microbiome: "genome_db_220315_AP"
ProjectPath: "/scratch/aprasad/211018_Medgenome_india_samples"
BackupPath: "/work/FAC/FBM/DMF/pengel/spirit/aprasad/20230313_apis_species_comparison/"
ResultsCopyPath: "/nas/FAC/FBM/DMF/pengel/spirit/D2c/aprasad/20211018_aprasad_ApisCrossSpeciesAnalysis/Analysis/20230313_apis_species_comparison/"
# BackupPath: "aiswarya@130.223.110.124:/home/aiswarya/mnt/aprasad/Backups/working_dir_backup/Cluster"
LocalBackup: False
# created used scripts/make_reads_list_file.py
PATHS_LIST_FILE: "/scratch/aprasad/20230313_apis_species_comparison/config/raw_file_paths.yaml"
SAMPLES_KE:
  - "AcCh01"
  - "AcCh02"
  - "AcCh03"
  - "AcCh04"
  - "AcCh05"
  - "AcCh06"
  - "AcCh07"
  - "AcCh08"
  - "AcCh09"
  - "AcCh10"
  - "AcKn01"
  - "AcKn02"
  - "AcKn03"
  - "AcKn04"
  - "AcKn05"
  - "AcKn06"
  - "AcKn07"
  - "AcKn08"
  - "AcKn09"
  - "AcKn10"
  - "AmAi01"
  - "AmAi02"
  - "AmAi03"
  - "AmAi04"
  - "AmAi05"
  - "AmAi06"
  - "AmAi07"
  - "AmAi08"
  - "AmAi09"
  - "AmAi10"
  - "AmIu01"
  - "AmIu02"
  - "AmIu03"
  - "AmIu04"
  - "AmIu05"
  - "AmIu06"
  - "AmIu07"
  - "AmIu08"
  - "AmIu09"
  - "AmIu10"
  - "DrY1_F1"
  - "DrY1_F2"
  - "DrY1_F3"
  - "DrY1_F4"
  - "DrY1_F5"
  - "DrY1_F6"
  - "DrY1_N1"
  - "DrY1_N2"
  - "DrY1_N3"
  - "DrY1_N4"
  - "DrY1_N5"
  - "DrY1_N6"
  - "DrY1_W1"
  - "DrY1_W2"
  - "DrY1_W3"
  - "DrY1_W4"
  - "DrY1_W5"
  - "DrY1_W6"
  - "DrY2_F1"
  - "DrY2_F2"
  - "DrY2_F3"
  - "DrY2_F4"
  - "DrY2_F5"
  # - "DrY2_F6"
  - "DrY2_N1"
  - "DrY2_N2"
  - "DrY2_N3"
  - "DrY2_N4"
  - "DrY2_N5"
  - "DrY2_N6"
  # - "DrY2_W1"
  # - "DrY2_W2"
  # - "DrY2_W3"
  # - "DrY2_W4"
  # - "DrY2_W5"
  # - "DrY2_W6"
  - "GrY2_F1"
  - "GrY2_F2"
  - "GrY2_F3"
  - "GrY2_F4"
  - "GrY2_F5"
  - "GrY2_F6"
  - "GrY2_N1"
  - "GrY2_N2"
  - "GrY2_N3"
  - "GrY2_N4"
  - "GrY2_N5"
  - "GrY2_N6"
  - "GrY2_W1"
  - "GrY2_W2"
  - "GrY2_W3"
  - "GrY2_W4"
  - "GrY2_W5"
  - "GrY2_W6"
SAMPLES_INDIA:
  - "C1-1"
  - "C1-2"
  - "C1-3"
  - "C1-4"
  - "C1-5"
  - "C2-1"
  - "C2-2"
  - "C2-3"
  - "C2-4"
  - "C2-5"
  - "C3-1"
  - "C3-2"
  - "C3-3"
  - "C3-4"
  - "C3-5"
  - "D1-1"
  - "D1-2"
  - "D1-3"
  - "D1-4"
  - "D1-5"
  - "D2-1"
  - "D2-2"
  - "D2-3"
  - "D2-4"
  - "D2-5"
  - "D3-1"
  - "D3-2"
  - "D3-3"
  - "D3-4"
  - "D3-5"
  - "F1-1"
  - "F1-2"
  - "F1-3"
  - "F1-4"
  - "F1-5"
  - "F2-1"
  - "F2-2"
  - "F2-3"
  - "F2-4"
  - "F2-5"
  - "F3-1"
  - "F3-2"
  - "F3-3"
  - "F3-4"
  - "F3-5"
  - "M1-1"
  - "M1-2"
  - "M1-3"
  - "M1-4"
  - "M1-5"
SAMPLES_MY:
  - "M2-1"
  - "M2-2"
  - "M2-3"
  - "M2-4"
  - "M2-5"
  - "M3-1"
  - "M3-2"
  - "M3-3"
  - "M3-4"
  - "M3-5"
  - "M4-1"
  - "M4-2"
  - "M4-3"
  - "M4-4"
  - "M4-5"
  - "M5-1"
  - "M5-2"
  - "M5-3"
  - "M5-4"
  - "M5-5"
  - "M6-1"
  - "M6-2"
  - "M6-3"
  - "M6-4"
  - "M6-5"
  - "M7-1"
  - "M7-2"
  - "M7-3"
  - "M7-4"
  - "M7-5"
  - "C4-1"
  - "C4-2"
  - "C4-3"
  - "C4-4"
  - "C4-5"
  - "C5-1"
  - "C5-2"
  - "C5-3"
  - "C5-4"
  - "C5-5"
  - "C6-1"
  - "C6-2"
  - "C6-3"
  - "C6-4"
  - "C6-5"
  - "C7-1"
  - "C7-2"
  - "C7-3"
  - "C7-4"
  - "C7-5"
  - "C8-1"
  - "C8-2"
  - "C8-3"
  - "C8-4"
  - "C8-5"
  - "C9-1"
  - "C9-2"
  - "C9-3"
  - "C9-4"
  - "C9-5"
  - "D4-1"
  - "D4-2"
  - "D4-3"
  - "D4-4"
  - "D4-5"
  - "D5-1"
  - "D5-2"
  - "D5-3"
  - "D5-4"
  - "D5-5"
  - "D6-1"
  - "D6-2"
  - "D6-3"
  - "D6-4"
  - "D6-5"
  - "D7-1"
  - "D7-2"
  - "D7-3"
  - "D7-4"
  - "D7-5"
  - "D8-1"
  - "D8-2"
  - "D8-3"
  - "D8-4"
  - "D8-5"
  - "D9-1"
  - "D9-2"
  - "D9-3"
  - "D9-4"
  - "D9-5"
  - "F4-1"
  - "F4-2"
  - "F4-3"
  - "F4-4"
  - "F4-5"
  - "F5-1"
  - "F5-2"
  - "F5-3"
  - "F5-4"
  - "F5-5"
  - "F6-1"
  - "F6-2"
  - "F6-3"
  - "F6-4"
  - "F6-5"
  - "F7-1"
  - "F7-2"
  - "F7-3"
  - "F7-4"
  - "F7-5"
  - "F8-1"
  - "F8-2"
  - "F8-3"
  - "F8-4"
  - "F8-5"
  - "F9-1"
  - "F9-2"
  - "F9-3"
  - "F9-4"
  - "F9-5"
  - "A1-1"
  - "A1-2"
  - "A1-3"
  - "A1-4"
  - "A1-5"
  - "A2-1"
  - "A2-2"
  - "A2-3"
  - "A2-4"
  - "A2-5"
  - "A3-1"
  - "A3-2"
  - "A3-3"
  - "A3-4"
  - "A3-5"
  - "A4-1"
  - "A4-2"
  - "A4-3"
  - "A4-4"
  - "A4-5"
  - "A5-1"
  - "A5-2"
  - "A5-3"
  - "A5-4"
  - "A5-5"
  - "A6-1"
  - "A6-2"
  - "A6-3"
  - "A6-4"
  - "A6-5"