# resume
RawdataPath: "/scratch/aprasad/20230313_apis_species_comparison/results/NGS_data/"
# RawdataPath: "/work/FAC/FBM/DMF/pengel/spirit/aprasad/20230313_apis_species_comparison/NGS_data/"
# RawdataPath: "/...path-to-NGS_data"
SAMPLES_KE:
  "AcCh01":
    - path_to_files
  "AcCh02":
    - path_to_files
  "AcCh03":
    - path_to_files
  "AcCh04":
    - path_to_files
  "AcCh05":
    - path_to_files
  "AcCh06":
    - path_to_files
  "AcCh07":
    - path_to_files
  "AcCh08":
    - path_to_files
  "AcCh09":
    - path_to_files
  "AcCh10":
    - path_to_files
  "AcKn01":
    - path_to_files
  "AcKn02":
    - path_to_files
  "AcKn03":
    - path_to_files
  "AcKn04":
    - path_to_files
  "AcKn05":
    - path_to_files
  "AcKn06":
    - path_to_files
  "AcKn07":
    - path_to_files
  "AcKn08":
    - path_to_files
  "AcKn09":
    - path_to_files
  "AcKn10":
    - path_to_files
  "AmAi01":
    - path_to_files
  "AmAi02":
    - path_to_files
  "AmAi03":
    - path_to_files
  "AmAi04":
    - path_to_files
  "AmAi05":
    - path_to_files
  "AmAi06":
    - path_to_files
  "AmAi07":
    - path_to_files
  "AmAi08":
    - path_to_files
  "AmAi09":
    - path_to_files
  "AmAi10":
    - path_to_files
  "AmIu01":
    - path_to_files
  "AmIu02":
    - path_to_files
  "AmIu03":
    - path_to_files
  "AmIu04":
    - path_to_files
  "AmIu05":
    - path_to_files
  "AmIu06":
    - path_to_files
  "AmIu07":
    - path_to_files
  "AmIu08":
    - path_to_files
  "AmIu09":
    - path_to_files
  "AmIu10":
    - path_to_files
  "DrY1_F1":
    - path_to_files
  "DrY1_F2":
    - path_to_files
  "DrY1_F3":
    - path_to_files
  "DrY1_F4":
    - path_to_files
  "DrY1_F5":
    - path_to_files
  "DrY1_F6":
    - path_to_files
  "DrY1_N1":
    - path_to_files
  "DrY1_N2":
    - path_to_files
  "DrY1_N3":
    - path_to_files
  "DrY1_N4":
    - path_to_files
  "DrY1_N5":
    - path_to_files
  "DrY1_N6":
    - path_to_files
  "DrY1_W1":
    - path_to_files
  "DrY1_W2":
    - path_to_files
  "DrY1_W3":
    - path_to_files
  "DrY1_W4":
    - path_to_files
  "DrY1_W5":
    - path_to_files
  "DrY1_W6":
    - path_to_files
  "DrY2_F1":
    - path_to_files
  "DrY2_F2":
    - path_to_files
  "DrY2_F3":
    - path_to_files
  "DrY2_F4":
    - path_to_files
  "DrY2_F5":
    - path_to_files
  "DrY2_F6":
    - path_to_files
  "DrY2_N1":
    - path_to_files
  "DrY2_N2":
    - path_to_files
  "DrY2_N3":
    - path_to_files
  "DrY2_N4":
    - path_to_files
  "DrY2_N5":
    - path_to_files
  "DrY2_N6":
    - path_to_files
  "DrY2_W1":
    - path_to_files
  "DrY2_W2":
    - path_to_files
  "DrY2_W3":
    - path_to_files
  "DrY2_W4":
    - path_to_files
  "DrY2_W5":
    - path_to_files
  "DrY2_W6":
    - path_to_files
  "GrY2_F1":
    - path_to_files
  "GrY2_F2":
    - path_to_files
  "GrY2_F3":
    - path_to_files
  "GrY2_F4":
    - path_to_files
  "GrY2_F5":
    - path_to_files
  "GrY2_F6":
    - path_to_files
  "GrY2_N1":
    - path_to_files
  "GrY2_N2":
    - path_to_files
  "GrY2_N3":
    - path_to_files
  "GrY2_N4":
    - path_to_files
  "GrY2_N5":
    - path_to_files
  "GrY2_N6":
    - path_to_files
  "GrY2_W1":
    - path_to_files
  "GrY2_W2":
    - path_to_files
  "GrY2_W3":
    - path_to_files
  "GrY2_W4":
    - path_to_files
  "GrY2_W5":
    - path_to_files
  "GrY2_W6":
    - path_to_files
SAMPLES_KE_CHOSEN:
  "AmAi01":
    - path_to_files
  "AmAi02":
    - path_to_files
  "AmAi03":
    - path_to_files
  "AmAi04":
    - path_to_files
  "AmAi05":
    - path_to_files
  "DrY2_F1":
    - path_to_files
  "DrY2_F2":
    - path_to_files
  "DrY2_F3":
    - path_to_files
  "DrY2_F4":
    - path_to_files
  "DrY2_F5":
    - path_to_files
SAMPLES_INDIA:
  "C1-1":
    - path_to_files
  "C1-2":
    - path_to_files
  "C1-3":
    - path_to_files
  "C1-4":
    - path_to_files
  "C1-5":
    - path_to_files
  "C2-1":
    - path_to_files
  "C2-2":
    - path_to_files
  "C2-3":
    - path_to_files
  "C2-4":
    - path_to_files
  "C2-5":
    - path_to_files
  "C3-1":
    - path_to_files
  "C3-2":
    - path_to_files
  "C3-3":
    - path_to_files
  "C3-4":
    - path_to_files
  "C3-5":
    - path_to_files
  "D1-1":
    - path_to_files
  "D1-2":
    - path_to_files
  "D1-3":
    - path_to_files
  "D1-4":
    - path_to_files
  "D1-5":
    - path_to_files
  "D2-1":
    - path_to_files
  "D2-2":
    - path_to_files
  "D2-3":
    - path_to_files
  "D2-4":
    - path_to_files
  "D2-5":
    - path_to_files
  "D3-1":
    - path_to_files
  "D3-2":
    - path_to_files
  "D3-3":
    - path_to_files
  "D3-4":
    - path_to_files
  "D3-5":
    - path_to_files
  "F1-1":
    - path_to_files
  "F1-2":
    - path_to_files
  "F1-3":
    - path_to_files
  "F1-4":
    - path_to_files
  "F1-5":
    - path_to_files
  "F2-1":
    - path_to_files
  "F2-2":
    - path_to_files
  "F2-3":
    - path_to_files
  "F2-4":
    - path_to_files
  "F2-5":
    - path_to_files
  "F3-1":
    - path_to_files
  "F3-2":
    - path_to_files
  "F3-3":
    - path_to_files
  "F3-4":
    - path_to_files
  "F3-5":
    - path_to_files
  "M1-1":
    - path_to_files
  "M1-2":
    - path_to_files
  "M1-3":
    - path_to_files
  "M1-4":
    - path_to_files
  "M1-5":
    - path_to_files
SAMPLES_MY:
  "M2-1":
    - path_to_files
  "M2-2":
    - path_to_files
  "M2-3":
    - path_to_files
  "M2-4":
    - path_to_files
  "M2-5":
    - path_to_files
  "M3-1":
    - path_to_files
  "M3-2":
    - path_to_files
  "M3-3":
    - path_to_files
  "M3-4":
    - path_to_files
  "M3-5":
    - path_to_files
  "M4-1":
    - path_to_files
  "M4-2":
    - path_to_files
  "M4-3":
    - path_to_files
  "M4-4":
    - path_to_files
  "M4-5":
    - path_to_files
  "M5-1":
    - path_to_files
  "M5-2":
    - path_to_files
  "M5-3":
    - path_to_files
  "M5-4":
    - path_to_files
  "M5-5":
    - path_to_files
  "M6-1":
    - path_to_files
  "M6-2":
    - path_to_files
  "M6-3":
    - path_to_files
  "M6-4":
    - path_to_files
  "M6-5":
    - path_to_files
  "M7-1":
    - path_to_files
  "M7-2":
    - path_to_files
  "M7-3":
    - path_to_files
  "M7-4":
    - path_to_files
  "M7-5":
    - path_to_files
  "C4-1":
    - path_to_files
  "C4-2":
    - path_to_files
  "C4-3":
    - path_to_files
  "C4-4":
    - path_to_files
  "C4-5":
    - path_to_files
  "C5-1":
    - path_to_files
  "C5-2":
    - path_to_files
  "C5-3":
    - path_to_files
  "C5-4":
    - path_to_files
  "C5-5":
    - path_to_files
  "C6-1":
    - path_to_files
  "C6-2":
    - path_to_files
  "C6-3":
    - path_to_files
  "C6-4":
    - path_to_files
  "C6-5":
    - path_to_files
  "C7-1":
    - path_to_files
  "C7-2":
    - path_to_files
  "C7-3":
    - path_to_files
  "C7-4":
    - path_to_files
  "C7-5":
    - path_to_files
  "C8-1":
    - path_to_files
  "C8-2":
    - path_to_files
  "C8-3":
    - path_to_files
  "C8-4":
    - path_to_files
  "C8-5":
    - path_to_files
  "C9-1":
    - path_to_files
  "C9-2":
    - path_to_files
  "C9-3":
    - path_to_files
  "C9-4":
    - path_to_files
  "C9-5":
    - path_to_files
  "D4-1":
    - path_to_files
  "D4-2":
    - path_to_files
  "D4-3":
    - path_to_files
  "D4-4":
    - path_to_files
  "D4-5":
    - path_to_files
  "D5-1":
    - path_to_files
  "D5-2":
    - path_to_files
  "D5-3":
    - path_to_files
  "D5-4":
    - path_to_files
  "D5-5":
    - path_to_files
  "D6-1":
    - path_to_files
  "D6-2":
    - path_to_files
  "D6-3":
    - path_to_files
  "D6-4":
    - path_to_files
  "D6-5":
    - path_to_files
  "D7-1":
    - path_to_files
  "D7-2":
    - path_to_files
  "D7-3":
    - path_to_files
  "D7-4":
    - path_to_files
  "D7-5":
    - path_to_files
  "D8-1":
    - path_to_files
  "D8-2":
    - path_to_files
  "D8-3":
    - path_to_files
  "D8-4":
    - path_to_files
  "D8-5":
    - path_to_files
  "D9-1":
    - path_to_files
  "D9-2":
    - path_to_files
  "D9-3":
    - path_to_files
  "D9-4":
    - path_to_files
  "D9-5":
    - path_to_files
  "F4-1":
    - path_to_files
  "F4-2":
    - path_to_files
  "F4-3":
    - path_to_files
  "F4-4":
    - path_to_files
  "F4-5":
    - path_to_files
  "F5-1":
    - path_to_files
  "F5-2":
    - path_to_files
  "F5-3":
    - path_to_files
  "F5-4":
    - path_to_files
  "F5-5":
    - path_to_files
  "F6-1":
    - path_to_files
  "F6-2":
    - path_to_files
  "F6-3":
    - path_to_files
  "F6-4":
    - path_to_files
  "F6-5":
    - path_to_files
  "F7-1":
    - path_to_files
  "F7-2":
    - path_to_files
  "F7-3":
    - path_to_files
  "F7-4":
    - path_to_files
  "F7-5":
    - path_to_files
  "F8-1":
    - path_to_files
  "F8-2":
    - path_to_files
  "F8-3":
    - path_to_files
  "F8-4":
    - path_to_files
  "F8-5":
    - path_to_files
  "F9-1":
    - path_to_files
  "F9-2":
    - path_to_files
  "F9-3":
    - path_to_files
  "F9-4":
    - path_to_files
  "F9-5":
    - path_to_files
  "A1-1":
    - path_to_files
  "A1-2":
    - path_to_files
  "A1-3":
    - path_to_files
  "A1-4":
    - path_to_files
  "A1-5":
    - path_to_files
  "A2-1":
    - path_to_files
  "A2-2":
    - path_to_files
  "A2-3":
    - path_to_files
  "A2-4":
    - path_to_files
  "A2-5":
    - path_to_files
  "A3-1":
    - path_to_files
  "A3-2":
    - path_to_files
  "A3-3":
    - path_to_files
  "A3-4":
    - path_to_files
  "A3-5":
    - path_to_files
  "A4-1":
    - path_to_files
  "A4-2":
    - path_to_files
  "A4-3":
    - path_to_files
  "A4-4":
    - path_to_files
  "A4-5":
    - path_to_files
  "A5-1":
    - path_to_files
  "A5-2":
    - path_to_files
  "A5-3":
    - path_to_files
  "A5-4":
    - path_to_files
  "A5-5":
    - path_to_files
  "A6-1":
    - path_to_files
  "A6-2":
    - path_to_files
  "A6-3":
    - path_to_files
  "A6-4":
    - path_to_files
  "A6-5":
    - path_to_files
READS:
  - "R1"
  - "R2"
Adapters:
  SAMPLES_KE: "config/NexteraPE-PE.fa"
  SAMPLES_KE_CHOSEN: "config/NexteraPE-PE.fa"
  # consider putting this in as a checkpoint if this needs to be made from index_table later
  SAMPLES_INDIA: "config/Adpaters-PE.fa"
  default: "config/NexteraPE-PE.fa"
TYPES:
  - "paired"
  - "unpaired"
ProjectIdentifier: "211018_Medgenome_india_samples"
GENOME_DBs:
  host: "4_host_db"
  microbiome_red: "honeybee_gut_microbiota_db_red"
  microbiome: "genome_db_220315_AP"
ProjectPath: "/scratch/aprasad/211018_Medgenome_india_samples"
BackupPath: "/work/FAC/FBM/DMF/pengel/spirit/aprasad/"
# BackupPath: "aiswarya@130.223.110.124:/home/aiswarya/mnt/aprasad/Backups/working_dir_backup/Cluster"
LocalBackup: False
