SAMPLES_KE:
    - "AcCh01"
    - "AcCh02"
    - "AcCh03"
    - "AcCh04"
    - "AcCh05"
    - "AcCh06"
    - "AcCh07"
    - "AcCh08"
    - "AcCh09"
    - "AcCh10"
    - "AcKn01"
    - "AcKn02"
    - "AcKn03"
    - "AcKn04"
    - "AcKn05"
    - "AcKn06"
    - "AcKn07"
    - "AcKn08"
    - "AcKn09"
    - "AcKn10"
    - "AmAi01"
    - "AmAi02"
    - "AmAi03"
    - "AmAi04"
    - "AmAi05"
    - "AmAi06"
    - "AmAi07"
    - "AmAi08"
    - "AmAi09"
    - "AmAi10"
    - "AmIu01"
    - "AmIu02"
    - "AmIu03"
    - "AmIu04"
    - "AmIu05"
    - "AmIu06"
    - "AmIu07"
    - "AmIu08"
    - "AmIu09"
    - "AmIu10"
    - "DrY1_F1"
    - "DrY1_F2"
    - "DrY1_F3"
    - "DrY1_F4"
    - "DrY1_F5"
    - "DrY1_F6"
    - "DrY1_N1"
    - "DrY1_N2"
    - "DrY1_N3"
    - "DrY1_N4"
    - "DrY1_N5"
    - "DrY1_N6"
    - "DrY1_W1"
    - "DrY1_W2"
    - "DrY1_W3"
    - "DrY1_W4"
    - "DrY1_W5"
    - "DrY1_W6"
    - "DrY2_F1"
    - "DrY2_F2"
    - "DrY2_F3"
    - "DrY2_F4"
    - "DrY2_F5"
    - "DrY2_F6"
    - "DrY2_N1"
    - "DrY2_N2"
    - "DrY2_N3"
    - "DrY2_N4"
    - "DrY2_N5"
    - "DrY2_N6"
    - "DrY2_W1"
    - "DrY2_W2"
    - "DrY2_W3"
    - "DrY2_W4"
    - "DrY2_W5"
    - "DrY2_W6"
    - "GrY2_F1"
    - "GrY2_F2"
    - "GrY2_F3"
    - "GrY2_F4"
    - "GrY2_F5"
    - "GrY2_F6"
    - "GrY2_N1"
    - "GrY2_N2"
    - "GrY2_N3"
    - "GrY2_N4"
    - "GrY2_N5"
    - "GrY2_N6"
    - "GrY2_W1"
    - "GrY2_W2"
    - "GrY2_W3"
    - "GrY2_W4"
    - "GrY2_W5"
    - "GrY2_W6"
SAMPLES_OLD:
  - "DrY2_F1"
  - "DrY2_F2"
  - "AcCh05"
  - "AcKn01"
  - "AmAi02"
  - "AmIu02"
SAMPLES_MIX:
  - "DrY2_F1"
  - "DrY2_F2"
  - "AcCh05"
  - "AcKn01"
  - "AmAi02"
  - "AmIu02"
  - "C1.1"
  - "C1.2"
  - "C1.3"
  - "C1.4"
  - "C1.5"
  - "C2.1"
  - "C2.2"
  - "C2.3"
  - "C2.4"
  - "C2.5"
  - "C3.1"
  - "C3.2"
  - "C3.3"
  - "C3.4"
  - "C3.5"
  - "D1.1"
  - "D1.2"
  - "D1.3"
  - "D1.4"
  - "D1.5"
  - "D2.1"
  - "D2.2"
  - "D2.3"
  - "D2.4"
  - "D2.5"
  - "D3.1"
  - "D3.2"
  - "D3.3"
  - "D3.4"
  - "D3.5"
  - "F1.1"
  - "F1.2"
  - "F1.3"
  - "F1.4"
  - "F1.5"
  - "F2.1"
  - "F2.2"
  - "F2.3"
  - "F2.4"
  - "F2.5"
  - "F3.1"
  - "F3.2"
  - "F3.3"
  - "F3.4"
  - "F3.5"
  - "M1.1"
  - "M1.2"
  - "M1.3"
  - "M1.4"
  - "M1.5"
SAMPLES_ALL:
  - "AcCh01"
  - "AcCh02"
  - "AcCh03"
  - "AcCh04"
  - "AcCh05"
  - "AcCh06"
  - "AcCh07"
  - "AcCh08"
  - "AcCh09"
  - "AcCh10"
  - "AcKn01"
  - "AcKn02"
  - "AcKn03"
  - "AcKn04"
  - "AcKn05"
  - "AcKn06"
  - "AcKn07"
  - "AcKn08"
  - "AcKn09"
  - "AcKn10"
  - "AmAi01"
  - "AmAi02"
  - "AmAi03"
  - "AmAi04"
  - "AmAi05"
  - "AmAi06"
  - "AmAi07"
  - "AmAi08"
  - "AmAi09"
  - "AmAi10"
  - "AmIu01"
  - "AmIu02"
  - "AmIu03"
  - "AmIu04"
  - "AmIu05"
  - "AmIu06"
  - "AmIu07"
  - "AmIu08"
  - "AmIu09"
  - "AmIu10"
  - "DrY1_F1"
  - "DrY1_F2"
  - "DrY1_F3"
  - "DrY1_F4"
  - "DrY1_F5"
  - "DrY1_F6"
  - "DrY1_N1"
  - "DrY1_N2"
  - "DrY1_N3"
  - "DrY1_N4"
  - "DrY1_N5"
  - "DrY1_N6"
  - "DrY1_W1"
  - "DrY1_W2"
  - "DrY1_W3"
  - "DrY1_W4"
  - "DrY1_W5"
  - "DrY1_W6"
  - "DrY2_F1"
  - "DrY2_F2"
  - "DrY2_F3"
  - "DrY2_F4"
  - "DrY2_F5"
  - "DrY2_F6"
  - "DrY2_N1"
  - "DrY2_N2"
  - "DrY2_N3"
  - "DrY2_N4"
  - "DrY2_N5"
  - "DrY2_N6"
  - "DrY2_W1"
  - "DrY2_W2"
  - "DrY2_W3"
  - "DrY2_W4"
  - "DrY2_W5"
  - "DrY2_W6"
  - "GrY2_F1"
  - "GrY2_F2"
  - "GrY2_F3"
  - "GrY2_F4"
  - "GrY2_F5"
  - "GrY2_F6"
  - "GrY2_N1"
  - "GrY2_N2"
  - "GrY2_N3"
  - "GrY2_N4"
  - "GrY2_N5"
  - "GrY2_N6"
  - "GrY2_W1"
  - "GrY2_W2"
  - "GrY2_W3"
  - "GrY2_W4"
  - "GrY2_W5"
  - "GrY2_W6"
  - "C1.1"
  - "C1.2"
  - "C1.3"
  - "C1.4"
  - "C1.5"
  - "C2.1"
  - "C2.2"
  - "C2.3"
  - "C2.4"
  - "C2.5"
  - "C3.1"
  - "C3.2"
  - "C3.3"
  - "C3.4"
  - "C3.5"
  - "D1.1"
  - "D1.2"
  - "D1.3"
  - "D1.4"
  - "D1.5"
  - "D2.1"
  - "D2.2"
  - "D2.3"
  - "D2.4"
  - "D2.5"
  - "D3.1"
  - "D3.2"
  - "D3.3"
  - "D3.4"
  - "D3.5"
  - "F1.1"
  - "F1.2"
  - "F1.3"
  - "F1.4"
  - "F1.5"
  - "F2.1"
  - "F2.2"
  - "F2.3"
  - "F2.4"
  - "F2.5"
  - "F3.1"
  - "F3.2"
  - "F3.3"
  - "F3.4"
  - "F3.5"
  - "M1.1"
  - "M1.2"
  - "M1.3"
  - "M1.4"
  - "M1.5"
SAMPLES_INDIA:
  - "C1.1"
  - "C1.2"
  - "C1.3"
  - "C1.4"
  - "C1.5"
  - "C2.1"
  - "C2.2"
  - "C2.3"
  - "C2.4"
  - "C2.5"
  - "C3.1"
  - "C3.2"
  - "C3.3"
  - "C3.4"
  - "C3.5"
  - "D1.1"
  - "D1.2"
  - "D1.3"
  - "D1.4"
  - "D1.5"
  - "D2.1"
  - "D2.2"
  - "D2.3"
  - "D2.4"
  - "D2.5"
  - "D3.1"
  - "D3.2"
  - "D3.3"
  - "D3.4"
  - "D3.5"
  - "F1.1"
  - "F1.2"
  - "F1.3"
  - "F1.4"
  - "F1.5"
  - "F2.1"
  - "F2.2"
  - "F2.3"
  - "F2.4"
  - "F2.5"
  - "F3.1"
  - "F3.2"
  - "F3.3"
  - "F3.4"
  - "F3.5"
  - "M1.1"
  - "M1.2"
  - "M1.3"
  - "M1.4"
  - "M1.5"
READS:
  - "R1"
  - "R2"
TYPES:
  - "paired"
  - "unpaired"
ProjectIdentifier: "211018_Medgenome_india_samples"
GENOME_DBs:
  # host_red: "host_db"
  host: "4_host_db"
  microbiome_red: "honeybee_gut_microbiota_db_red"
  microbiome: "genome_db_220315_AP"
ProjectPath: "/scratch/aprasad/211018_Medgenome_india_samples"
