name: midas-env

channels:
  - bioconda
  - conda-forge
  - hcc

dependencies:
  - python=3.6.8
  - biopython>=1.62
  - numpy>=1.7.0
  - pysam>=0.8.1
  - pandas>=0.17.1
  - hmmer
  - vsearch
  - hs-blastn
  - bowtie2
  - samtools
